import { GAME_CONFIG, STATUS, formatDuration } from './game-data.js';
import { adminLogin } from './auth.js';
import { listTeams, resetTeam, resetAll, saveTeamState } from './storage.js';
import { qrImageUrl, checkpointUrl, printQrCards } from './qr.js';
const login = document.querySelector('#adminLogin'); const dashboard = document.querySelector('#adminDashboard'); const teamsPanel = document.querySelector('#adminTeams');
const renderTeams = (states) => { teamsPanel.innerHTML = states.map((state) => { const team = GAME_CONFIG.teams.find((item) => item.id === state.teamId); const elapsed = state.startTime ? formatDuration((state.completionTime || Date.now()) - state.startTime) : '00:00'; return `<article class="admin-row"><div><strong style="color:${team.color}">${team.emoji} ${team.name}</strong><span>${state.status} · checkpoint ${state.currentStage}/${team.route.length} · ${elapsed}</span><small>${state.currentLocation ? (GAME_CONFIG.locations[state.currentLocation]?.shortName || 'CORE FINAL') : 'No current destination'}</small></div><div class="admin-actions"><button data-action="advance" data-id="${team.id}" class="mini">Complete stage</button><button data-action="reset" data-id="${team.id}" class="mini danger">Reset</button></div></article>`; }).join(''); };
async function refresh() { renderTeams(await listTeams()); }
document.querySelector('#adminForm').addEventListener('submit', (event) => { event.preventDefault(); if (!adminLogin(document.querySelector('#adminPin').value)) { document.querySelector('#adminError').textContent = 'Invalid admin PIN.'; return; } login.classList.add('is-hidden'); dashboard.classList.remove('is-hidden'); refresh(); });
teamsPanel.addEventListener('click', async (event) => { const button = event.target.closest('[data-action]'); if (!button) return; const id = button.dataset.id; if (button.dataset.action === 'reset' && window.confirm('Reset this team and erase its progress?')) await resetTeam(id); if (button.dataset.action === 'advance') { const state = (await listTeams()).find((item) => item.teamId === id); const team = GAME_CONFIG.teams.find((item) => item.id === id); if (state.status === STATUS.NOT_STARTED) { state.status = STATUS.IN_PROGRESS; state.startTime = Date.now(); } if (state.currentStage < team.route.length) state.currentStage += 1; state.unlocked = false; state.currentLocation = null; await saveTeamState(id, state); } refresh(); });
document.querySelector('#resetAll').onclick = async () => { if (window.confirm('Reset every team and erase the full event state?')) { await resetAll(); refresh(); } };
const qrGrid = document.querySelector('#qrGrid'); qrGrid.innerHTML = [...Object.entries(GAME_CONFIG.locations), ['final_core', { name: 'CORE Final', shortName: 'FINAL CORE', code: GAME_CONFIG.finalCode }]].map(([id, point]) => `<article class="qr-card"><h3>${point.name}</h3><img src="${qrImageUrl(checkpointUrl(id))}" alt="QR code for ${point.name}"><code>${point.code}</code></article>`).join(''); document.querySelector('#printQr').onclick = () => printQrCards(qrGrid);
